blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/LastandDevelopment/MeteorExtinctionOfficial/discussions
    about: If you want to tell me your opinion on the game, post it in the discussions tab.
