name: Feature Request
description: Post your idea for a new feature here.
title: "Feature Request: "
labels: "request"
body:
  - type: markdown
    attributes:
      value: |
        Before posting your feature request, please make sure that feature does not exist in the newest version of the game. You can download the latest version on: https://sites.google.com/view/lastanddevelopment/meteor-extinction/all-versions
        
        ---
        
  - type: dropdown
    id: edition
    attributes:
      label: Game Edition
      description: "In which edition of the game do you want this feature?"
      options:
        - Android
        - PC
    validations:
      required: true
  - type: textarea
    id: featuredescription
    attributes:
      label: Feature description
      description: Describe your idea for a new feature.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why do you want this feature to be in the game?
